// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVcR3ubRZHiEAUWdyh8z8zKv32yuggla0',
    appId: '1:684586790343:web:f4b2585f2469d1082ebde2',
    messagingSenderId: '684586790343',
    projectId: 'myfest-db88e',
    authDomain: 'myfest-db88e.firebaseapp.com',
    databaseURL: 'https://myfest-db88e-default-rtdb.firebaseio.com',
    storageBucket: 'myfest-db88e.appspot.com',
    measurementId: 'G-P4YFC3C2W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshAwmTQuDGw7_rGAZTPdRA3xdQH_V6q8',
    appId: '1:684586790343:android:4f801299d1fe5fb22ebde2',
    messagingSenderId: '684586790343',
    projectId: 'myfest-db88e',
    databaseURL: 'https://myfest-db88e-default-rtdb.firebaseio.com',
    storageBucket: 'myfest-db88e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9YLf2pEx3rBBiqeoBiMQx4ufCmHs04nU',
    appId: '1:684586790343:ios:6fa1b2ba1e8360e02ebde2',
    messagingSenderId: '684586790343',
    projectId: 'myfest-db88e',
    databaseURL: 'https://myfest-db88e-default-rtdb.firebaseio.com',
    storageBucket: 'myfest-db88e.appspot.com',
    iosClientId: '684586790343-b1qhivms13dt912o8sps5hn3a6k35h08.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9YLf2pEx3rBBiqeoBiMQx4ufCmHs04nU',
    appId: '1:684586790343:ios:6fa1b2ba1e8360e02ebde2',
    messagingSenderId: '684586790343',
    projectId: 'myfest-db88e',
    databaseURL: 'https://myfest-db88e-default-rtdb.firebaseio.com',
    storageBucket: 'myfest-db88e.appspot.com',
    iosClientId: '684586790343-b1qhivms13dt912o8sps5hn3a6k35h08.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfest',
  );
}
